// lib/languages.ts
import type { Language } from '@/types';

export const LANGUAGES: Language[] = [
  // 22 Scheduled Languages
  { code: 'as', name: 'Assamese', nativeName: 'অসমীয়া', isScheduled: true },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা', isScheduled: true },
  { code: 'bodo', name: 'Bodo', nativeName: 'बड़ो', isScheduled: true },
  { code: 'doi', name: 'Dogri', nativeName: 'डोगरी', isScheduled: true },
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી', isScheduled: true },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', isScheduled: true },
  { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ', isScheduled: true },
  { code: 'ks', name: 'Kashmiri', nativeName: 'कॉशुर', isScheduled: true },
  { code: 'kok', name: 'Konkani', nativeName: 'कोंकणी', isScheduled: true },
  { code: 'mai', name: 'Maithili', nativeName: 'मैथिली', isScheduled: true },
  { code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം', isScheduled: true },
  { code: 'mni', name: 'Manipuri', nativeName: 'মৈতৈলোন্', isScheduled: true },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी', isScheduled: true },
  { code: 'ne', name: 'Nepali', nativeName: 'नेपाली', isScheduled: true },
  { code: 'or', name: 'Odia', nativeName: 'ଓଡ଼ିଆ', isScheduled: true },
  { code: 'pa', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ', isScheduled: true },
  { code: 'sa', name: 'Sanskrit', nativeName: 'संस्कृतम्', isScheduled: true },
  { code: 'sat', name: 'Santali', nativeName: 'ᱥᱟᱱᱛᱟᱲᱤ', isScheduled: true },
  { code: 'sd', name: 'Sindhi', nativeName: 'سنڌي', isScheduled: true },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்', isScheduled: true },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు', isScheduled: true },
  { code: 'ur', name: 'Urdu', nativeName: 'اردو', isScheduled: true },
  // Additional regional languages
  { code: 'awa', name: 'Awadhi', nativeName: 'अवधी', isScheduled: false },
  { code: 'bgc', name: 'Haryanvi', nativeName: 'हरियाणवी', isScheduled: false },
  { code: 'bhb', name: 'Bhili', nativeName: 'भीली', isScheduled: false },
  { code: 'bhi', name: 'Bhilali', nativeName: 'भिलाली', isScheduled: false },
  { code: 'bho', name: 'Bhojpuri', nativeName: 'भोजपुरी', isScheduled: false },
  { code: 'bra', name: 'Braj', nativeName: 'ब्रज भाषा', isScheduled: false },
  { code: 'brj', name: 'Braj Bhasha', nativeName: 'ब्रज', isScheduled: false },
  { code: 'cgg', name: 'Chiga', nativeName: 'Rukiga', isScheduled: false },
  { code: 'gbm', name: 'Garhwali', nativeName: 'गढ़वाली', isScheduled: false },
  { code: 'gon', name: 'Gondi', nativeName: 'గోండి', isScheduled: false },
  { code: 'guj', name: 'Gujari', nativeName: 'गुजरी', isScheduled: false },
  { code: 'hne', name: 'Chhattisgarhi', nativeName: 'छत्तीसगढ़ी', isScheduled: false },
  { code: 'ho', name: 'Ho', nativeName: '𑣸𑣷', isScheduled: false },
  { code: 'kfy', name: 'Kumaoni', nativeName: 'कुमाऊँनी', isScheduled: false },
  { code: 'kha', name: 'Khasi', nativeName: 'Ka Ktien Khasi', isScheduled: false },
  { code: 'khn', name: 'Khandeshi', nativeName: 'खानदेशी', isScheduled: false },
  { code: 'kru', name: 'Kurukh', nativeName: 'कुड़ुख़', isScheduled: false },
  { code: 'lus', name: 'Mizo', nativeName: 'Mizo ṭawng', isScheduled: false },
  { code: 'mag', name: 'Magahi', nativeName: 'मगही', isScheduled: false },
  { code: 'mar', name: 'Malvi', nativeName: 'माळवी', isScheduled: false },
  { code: 'mtr', name: 'Mewari', nativeName: 'मेवाड़ी', isScheduled: false },
  { code: 'mup', name: 'Malvi Punjabi', nativeName: 'मालवी', isScheduled: false },
  { code: 'nag', name: 'Naga Pidgin', nativeName: 'Nagamese', isScheduled: false },
  { code: 'noe', name: 'Nimadi', nativeName: 'निमाड़ी', isScheduled: false },
  { code: 'raj', name: 'Rajasthani', nativeName: 'राजस्थानी', isScheduled: false },
  { code: 'sck', name: 'Sadri', nativeName: 'सदरी', isScheduled: false },
  { code: 'srx', name: 'Sirmauri', nativeName: 'सिरमौरी', isScheduled: false },
  { code: 'tcy', name: 'Tulu', nativeName: 'ತುಳು', isScheduled: false },
  { code: 'tharu', name: 'Tharu', nativeName: 'थारू', isScheduled: false },
  { code: 'unr', name: 'Mundari', nativeName: 'मुंडारी', isScheduled: false },
  { code: 'vah', name: 'Varhadi', nativeName: 'वऱ्हाडी', isScheduled: false },
  { code: 'wbq', name: 'Wadiyara Koli', nativeName: 'वाडियारा कोली', isScheduled: false },
  { code: 'xnr', name: 'Kangri', nativeName: 'कांगड़ी', isScheduled: false },
  // More scheduled/major languages
  { code: 'en', name: 'English', nativeName: 'English', isScheduled: false },
  { code: 'ach', name: 'Acholi', nativeName: 'Acholi', isScheduled: false },
  { code: 'adh', name: 'Adhola', nativeName: 'Adhola', isScheduled: false },
  { code: 'alr', name: 'Alutor', nativeName: 'Alutor', isScheduled: false },
  { code: 'ang', name: 'Anglo', nativeName: 'Anglo', isScheduled: false },
  { code: 'aot', name: 'Atong', nativeName: 'Atong', isScheduled: false },
  { code: 'ape', name: 'Bukiyip', nativeName: 'Bukiyip', isScheduled: false },
  { code: 'bap', name: 'Bangru', nativeName: 'बांगरू', isScheduled: false },
  { code: 'bcq', name: 'Bench', nativeName: 'Bench', isScheduled: false },
  { code: 'bfw', name: 'Bondo', nativeName: 'Bondo', isScheduled: false },
  { code: 'bgq', name: 'Bagri', nativeName: 'बागड़ी', isScheduled: false },
  { code: 'bns', name: 'Bundeli', nativeName: 'बुन्देली', isScheduled: false },
  { code: 'bpy', name: 'Bishnupriya', nativeName: 'বিষ্ণুপ্রিয়া মণিপুরী', isScheduled: false },
  { code: 'cep', name: 'Cepang', nativeName: 'Cepang', isScheduled: false },
  { code: 'ckb', name: 'Sorani', nativeName: 'سۆرانی', isScheduled: false },
  { code: 'dcc', name: 'Deccan', nativeName: 'دکنی', isScheduled: false },
  { code: 'dgo', name: 'Dogri (Dogra)', nativeName: 'ڈوگری', isScheduled: false },
  { code: 'dhi', name: 'Dhimal', nativeName: 'Dhimal', isScheduled: false },
  { code: 'dne', name: 'Nendza', nativeName: 'Nendza', isScheduled: false },
  { code: 'dzo', name: 'Dzongkha', nativeName: 'རྫོང་ཁ', isScheduled: false },
  { code: 'ekk', name: 'Estonian', nativeName: 'eesti keel', isScheduled: false },
  { code: 'fij', name: 'Fijian', nativeName: 'Vosa Vakaviti', isScheduled: false },
  { code: 'gad', name: 'Gade Lohar', nativeName: 'Gade', isScheduled: false },
  { code: 'gag', name: 'Gagauz', nativeName: 'Gagauz', isScheduled: false },
  { code: 'grt', name: 'Garo', nativeName: 'Garo', isScheduled: false },
  { code: 'hoc', name: 'Ho (Munda)', nativeName: 'Ho', isScheduled: false },
  { code: 'kek', name: 'Kekchi', nativeName: "Q'eqchi'", isScheduled: false },
  { code: 'kfr', name: 'Kachhi', nativeName: 'कच्छी', isScheduled: false },
  { code: 'kfy2', name: 'Kumauni', nativeName: 'कुमाऊँनी', isScheduled: false },
  { code: 'kha2', name: 'Kharia', nativeName: 'Kharia', isScheduled: false },
  { code: 'khn2', name: 'Khandeshi (Ahirani)', nativeName: 'अहिराणी', isScheduled: false },
  { code: 'kln', name: 'Nandi', nativeName: 'Kalenjin', isScheduled: false },
  { code: 'koc', name: 'Kochila Tharu', nativeName: 'Kochila', isScheduled: false },
  { code: 'koi', name: 'Komi-Permyak', nativeName: 'Коми-пермяцкӧй', isScheduled: false },
  { code: 'lep', name: 'Lepcha', nativeName: 'ᰛᰩᰧᰵ', isScheduled: false },
  { code: 'lif', name: 'Limbu', nativeName: 'ᤕᤠᤰᤌᤢᤱ', isScheduled: false },
  { code: 'ljp', name: 'Lampung', nativeName: 'Lampung', isScheduled: false },
  { code: 'maw', name: 'Mampruli', nativeName: 'Mampelle', isScheduled: false },
  { code: 'mbd', name: 'Mandari', nativeName: 'Mandari', isScheduled: false },
  { code: 'mgp', name: 'Magai', nativeName: 'Magai Kanuri', isScheduled: false },
  { code: 'mgy', name: 'Mambwe-Lungu', nativeName: 'Mambwe', isScheduled: false },
  { code: 'mkb', name: 'Mal Paharia', nativeName: 'Mal', isScheduled: false },
  { code: 'mni2', name: 'Meitei', nativeName: 'মেইতেই', isScheduled: false },
  { code: 'mtm', name: 'Mator', nativeName: 'Mator', isScheduled: false },
  { code: 'mwr', name: 'Marwari', nativeName: 'मारवाड़ी', isScheduled: false },
  { code: 'nag2', name: 'Nagamese Creole', nativeName: 'Nagamese', isScheduled: false },
  { code: 'nas', name: 'Naskapi', nativeName: 'Naskapi', isScheduled: false },
  { code: 'ndb', name: 'Kenswei Nsei', nativeName: 'Kenswei', isScheduled: false },
  { code: 'nds', name: 'Low German', nativeName: 'Plattdüütsch', isScheduled: false },
  { code: 'nep', name: 'Nepalese', nativeName: 'नेपाली', isScheduled: false },
  { code: 'new', name: 'Newari', nativeName: 'नेवाः', isScheduled: false },
  { code: 'nga', name: 'Ngbaka', nativeName: 'Ngbaka', isScheduled: false },
  { code: 'ngp', name: 'Ngulu', nativeName: 'Ngulu', isScheduled: false },
  { code: 'nhe', name: 'Nahuatl', nativeName: 'Nāhuatl', isScheduled: false },
  { code: 'nhr', name: 'Nharo', nativeName: 'Nharo', isScheduled: false },
  { code: 'niw', name: 'Nimo', nativeName: 'Nimo', isScheduled: false },
  { code: 'nsk', name: 'Naskapi', nativeName: 'Naskapi', isScheduled: false },
  { code: 'nwi', name: 'Southwest Tanna', nativeName: 'Southwest Tanna', isScheduled: false },
  { code: 'ory', name: 'Oraon Sadri', nativeName: 'Oraon', isScheduled: false },
  { code: 'pcm', name: 'Nigerian Pidgin', nativeName: 'Naijá', isScheduled: false },
  { code: 'phl', name: 'Phalura', nativeName: 'پھلوڑا', isScheduled: false },
  { code: 'plk', name: 'Polish', nativeName: 'Polski', isScheduled: false },
  { code: 'pnb', name: 'Western Punjabi', nativeName: 'پنجابی', isScheduled: false },
  { code: 'poc', name: 'Pocomam', nativeName: 'Poqomam', isScheduled: false },
  { code: 'rkt', name: 'Rangpuri', nativeName: 'রংপুরী', isScheduled: false },
  { code: 'rwr', name: 'Marwari (Alt)', nativeName: 'मारवाड़ी', isScheduled: false },
  { code: 'sas', name: 'Sasak', nativeName: 'Sasak', isScheduled: false },
  { code: 'saz', name: 'Saurashtra', nativeName: 'ꢱꣃꢬꢵꢰ꣄ꢜ꣄ꢬ', isScheduled: false },
  { code: 'sck2', name: 'Sadani', nativeName: 'सादरी', isScheduled: false },
  { code: 'sgj', name: 'Surgujia', nativeName: 'सरगुजिया', isScheduled: false },
  { code: 'sh', name: 'Serbo-Croatian', nativeName: 'Srpskohrvatski', isScheduled: false },
  { code: 'shi', name: 'Tachelhit', nativeName: 'ⵜⴰⵛⵍⵃⵉⵜ', isScheduled: false },
  { code: 'shn', name: 'Shan', nativeName: 'ၽႃႇသႃႇတႆး', isScheduled: false },
  { code: 'skr', name: 'Seraiki', nativeName: 'سرائیکی', isScheduled: false },
  { code: 'sog', name: 'Sogdian', nativeName: 'Sogdian', isScheduled: false },
  { code: 'srm', name: 'Saramaccan', nativeName: 'Saamáka', isScheduled: false },
  { code: 'sux', name: 'Sumerian', nativeName: 'Sumerian', isScheduled: false },
  { code: 'syl', name: 'Sylheti', nativeName: 'ꠍꠤꠟꠐꠤ', isScheduled: false },
  { code: 'tnl', name: 'Lisela', nativeName: 'Lisela', isScheduled: false },
  { code: 'tok', name: 'Toki Pona', nativeName: 'toki pona', isScheduled: false },
  { code: 'tsg', name: 'Tausug', nativeName: 'Bahasa Sūg', isScheduled: false },
  { code: 'ttq', name: 'Tawallammat Tamajaq', nativeName: 'Tawallammat Tamajaq', isScheduled: false },
  { code: 'tuo', name: 'Tucano', nativeName: 'Tukano', isScheduled: false },
  { code: 'var', name: 'Huarijio', nativeName: 'Huarijío', isScheduled: false },
  { code: 'vec', name: 'Venetian', nativeName: 'Vèneto', isScheduled: false },
  { code: 'vep', name: 'Veps', nativeName: 'Vepsän', isScheduled: false },
  { code: 'vmw', name: 'Makhuwa', nativeName: 'Makhuwa', isScheduled: false },
  { code: 'wls', name: 'Wallisian', nativeName: 'Fakauvea', isScheduled: false },
  { code: 'wni', name: 'Ndzwani Comorian', nativeName: 'Shimasiwa', isScheduled: false },
  { code: 'xog', name: 'Soga', nativeName: 'Olusoga', isScheduled: false },
  { code: 'yrk', name: 'Nenets', nativeName: 'Ненэцяʼ вада', isScheduled: false },
  { code: 'yua', name: 'Yucatec Maya', nativeName: "Maaya T'aan", isScheduled: false },
  { code: 'zbu', name: 'Bu-Nao Bunu', nativeName: 'Bu-Nao', isScheduled: false },
  { code: 'zne', name: 'Zande', nativeName: 'Pazande', isScheduled: false },
];

export const SCHEDULED_LANGUAGES = LANGUAGES.filter((l) => l.isScheduled);

export const TOP_LANGUAGES = [
  'en', 'hi', 'bn', 'te', 'ta', 'mr', 'gu', 'kn', 'ml', 'pa', 'or', 'as',
];

export function getLanguageByCode(code: string): Language | undefined {
  return LANGUAGES.find((l) => l.code === code);
}
